---
- name: "Ensure HAProxy is installed"
  yum:
    name: haproxy
    state: installed
  become: true

- name: "Ensure rsyslog is installed"
  yum:
    name: rsyslog
    state: installed
  become: true

- name: "Ensure logrotate is installed"
  yum:
    name: logrotate
    state: installed
  become: true

- name: "Configure syslog to accept network log events"
  lineinfile:
    path: /etc/sysconfig/rsyslog
    regexp: '^SYSLOGD_OPTIONS=""'
    line: 'SYSLOGD_OPTIONS="-r"'
  become: true

- name: "Copy rsyslog HAProxy configuration"
  template:
    src: "rsyslog.conf.j2"
    dest: "/etc/rsyslog.d/haproxy.conf"
  notify: restart rsyslog
  become: true

- name: "Copy logrotate HAProxy configuration"
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.d/haproxy"
  become: true


- name: "Get HAProxy version"
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no
  become: true

- name: "Set HAProxy version"
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: "Copy HAProxy configuration in place"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    mode: 0644
    validate: "haproxy -f %s -c -q"
  notify: restart haproxy
  become: true

- name: "Ensure HAProxy is started and enabled on boot"
  service:
    name: haproxy
    enabled: yes
  become: true